spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
#        defer-datasource-initialization: true
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/dogstar
        username: sa
        password:
    h2:
        console:
            enabled: true
