spring:
    jpa:
        show-sql: true
        hibernate:
#            ddl-auto: create
            hbm2ddl.auto: update
        properties:
            hibernate:
                format_sql: true
#        defer-datasource-initialization: true
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/dogstar
        username: sa
        password:
    h2:
        console:
            enabled: true
jwt:
    issuer: tokenIssuer
    secret_key: study